<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\README.md" />
		<None Include="..\ROADMAP.md" />
		<None Include="..\CHANGELOG.md" />

		<None Include="..\metadata\**\*" />
		<None Include="..\docs\**\*" />
	</ItemGroup>

</Project>